name = "demo-twitter-api"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "demo-twitter-db"
database_id = "local-dev-db"
